// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chart_annotations.sql

package storepg

import "context"

const deleteChartAnnotationsForEntity = `-- name: DeleteChartAnnotationsForEntity :exec
DELETE FROM chart_annotations WHERE user_id = $1 AND entity_type = $2 AND entity_id = $3
`

type DeleteChartAnnotationsForEntityParams struct {
	UserID     string `json:"user_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) DeleteChartAnnotationsForEntity(ctx context.Context, arg DeleteChartAnnotationsForEntityParams) error {
	_, err := q.db.ExecContext(ctx, deleteChartAnnotationsForEntity, arg.UserID, arg.EntityType, arg.EntityID)
	return err
}

const getChartAnnotation = `-- name: GetChartAnnotation :one
SELECT user_id, entity_type, entity_id, symbol, interval, drawings, updated_at FROM chart_annotations
WHERE user_id = $1 AND entity_type = $2 AND entity_id = $3 AND symbol = $4 AND interval = $5
`

type GetChartAnnotationParams struct {
	UserID     string `json:"user_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Symbol     string `json:"symbol"`
	Interval   string `json:"interval"`
}

func (q *Queries) GetChartAnnotation(ctx context.Context, arg GetChartAnnotationParams) (ChartAnnotation, error) {
	row := q.db.QueryRowContext(ctx, getChartAnnotation, arg.UserID, arg.EntityType, arg.EntityID, arg.Symbol, arg.Interval)
	var i ChartAnnotation
	err := row.Scan(&i.UserID, &i.EntityType, &i.EntityID, &i.Symbol, &i.Interval, &i.Drawings, &i.UpdatedAt)
	return i, err
}

const upsertChartAnnotation = `-- name: UpsertChartAnnotation :one
INSERT INTO chart_annotations (user_id, entity_type, entity_id, symbol, interval, drawings, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)
ON CONFLICT(user_id, entity_type, entity_id, symbol, interval) DO UPDATE SET
    drawings = excluded.drawings,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, entity_type, entity_id, symbol, interval, drawings, updated_at
`

type UpsertChartAnnotationParams struct {
	UserID     string `json:"user_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Symbol     string `json:"symbol"`
	Interval   string `json:"interval"`
	Drawings   string `json:"drawings"`
}

func (q *Queries) UpsertChartAnnotation(ctx context.Context, arg UpsertChartAnnotationParams) (ChartAnnotation, error) {
	row := q.db.QueryRowContext(ctx, upsertChartAnnotation, arg.UserID, arg.EntityType, arg.EntityID, arg.Symbol, arg.Interval, arg.Drawings)
	var i ChartAnnotation
	err := row.Scan(&i.UserID, &i.EntityType, &i.EntityID, &i.Symbol, &i.Interval, &i.Drawings, &i.UpdatedAt)
	return i, err
}
