// Code generated by sqlc style overlay. DO NOT EDIT BY HAND OUTSIDE THE OVERLAY TASK.

package storepg

import (
	"context"
	"database/sql"
	"time"
)

type CommercialFeedSetting struct {
	ID           int32     `json:"id"`
	NewsProvider string    `json:"news_provider"`
	PaidProvider string    `json:"paid_provider"`
	ApiBaseUrl   string    `json:"api_base_url"`
	ApiKey       string    `json:"api_key"`
	LicenseNote  string    `json:"license_note"`
	UpdatedAt    time.Time `json:"updated_at"`
}

const getCommercialFeedSettings = `SELECT id, news_provider, paid_provider, api_base_url, api_key, license_note, updated_at
FROM commercial_feed_settings
WHERE id = 1`

func (q *Queries) GetCommercialFeedSettings(ctx context.Context) (CommercialFeedSetting, error) {
	row := q.db.QueryRowContext(ctx, getCommercialFeedSettings)
	var i CommercialFeedSetting
	err := row.Scan(
		&i.ID,
		&i.NewsProvider,
		&i.PaidProvider,
		&i.ApiBaseUrl,
		&i.ApiKey,
		&i.LicenseNote,
		&i.UpdatedAt,
	)
	return i, err
}

type UpsertCommercialFeedSettingsParams struct {
	NewsProvider string `json:"news_provider"`
	PaidProvider string `json:"paid_provider"`
	ApiBaseUrl   string `json:"api_base_url"`
	ApiKey       string `json:"api_key"`
	LicenseNote  string `json:"license_note"`
}

const upsertCommercialFeedSettings = `INSERT INTO commercial_feed_settings (id, news_provider, paid_provider, api_base_url, api_key, license_note, updated_at)
VALUES (1, $1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    news_provider = excluded.news_provider,
    paid_provider = excluded.paid_provider,
    api_base_url = excluded.api_base_url,
    api_key = excluded.api_key,
    license_note = excluded.license_note,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, news_provider, paid_provider, api_base_url, api_key, license_note, updated_at`

func (q *Queries) UpsertCommercialFeedSettings(ctx context.Context, arg UpsertCommercialFeedSettingsParams) (CommercialFeedSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertCommercialFeedSettings,
		arg.NewsProvider,
		arg.PaidProvider,
		arg.ApiBaseUrl,
		arg.ApiKey,
		arg.LicenseNote,
	)
	var i CommercialFeedSetting
	err := row.Scan(
		&i.ID,
		&i.NewsProvider,
		&i.PaidProvider,
		&i.ApiBaseUrl,
		&i.ApiKey,
		&i.LicenseNote,
		&i.UpdatedAt,
	)
	if err == sql.ErrNoRows {
		return CommercialFeedSetting{}, err
	}
	return i, err
}

