// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package storepg

import (
	"context"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (id, user_id, body, page, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'open', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, body, page, status, created_at, updated_at
`

type CreateFeedbackParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Body   string `json:"body"`
	Page   string `json:"page"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback, arg.ID, arg.UserID, arg.Body, arg.Page)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.Page,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedbackByUser = `-- name: ListFeedbackByUser :many
SELECT id, user_id, body, page, status, created_at, updated_at
FROM feedback
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFeedbackByUser(ctx context.Context, userID string) ([]Feedback, error) {
	rows, err := q.db.QueryContext(ctx, listFeedbackByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feedback
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.Page,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
