// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: psychology_questions.sql

package storepg

import (
	"context"
)

const getPsychologyQuestions = `-- name: GetPsychologyQuestions :one
SELECT user_id, questions, updated_at FROM psychology_question_settings WHERE user_id = $1
`

func (q *Queries) GetPsychologyQuestions(ctx context.Context, userID string) (PsychologyQuestionSetting, error) {
	row := q.db.QueryRowContext(ctx, getPsychologyQuestions, userID)
	var i PsychologyQuestionSetting
	err := row.Scan(&i.UserID, &i.Questions, &i.UpdatedAt)
	return i, err
}

const upsertPsychologyQuestions = `-- name: UpsertPsychologyQuestions :one
INSERT INTO psychology_question_settings (user_id, questions, updated_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    questions = excluded.questions,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, questions, updated_at
`

type UpsertPsychologyQuestionsParams struct {
	UserID    string `json:"user_id"`
	Questions string `json:"questions"`
}

func (q *Queries) UpsertPsychologyQuestions(ctx context.Context, arg UpsertPsychologyQuestionsParams) (PsychologyQuestionSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertPsychologyQuestions, arg.UserID, arg.Questions)
	var i PsychologyQuestionSetting
	err := row.Scan(&i.UserID, &i.Questions, &i.UpdatedAt)
	return i, err
}
