// Code generated by sqlc style overlay. DO NOT EDIT BY HAND OUTSIDE THE OVERLAY TASK.
package store

import (
	"context"
)

const getAnalyticsEmailSettings = `SELECT user_id, enabled, email, timezone, daily, weekly, monthly, metrics_json, last_daily_sent_for, last_weekly_sent_for, last_monthly_sent_for, updated_at
FROM analytics_email_settings
WHERE user_id = ?`

func (q *Queries) GetAnalyticsEmailSettings(ctx context.Context, userID string) (AnalyticsEmailSetting, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticsEmailSettings, userID)
	var i AnalyticsEmailSetting
	err := row.Scan(&i.UserID, &i.Enabled, &i.Email, &i.Timezone, &i.Daily, &i.Weekly, &i.Monthly, &i.MetricsJson, &i.LastDailySentFor, &i.LastWeeklySentFor, &i.LastMonthlySentFor, &i.UpdatedAt)
	return i, err
}

const listEnabledAnalyticsEmailSettings = `SELECT user_id, enabled, email, timezone, daily, weekly, monthly, metrics_json, last_daily_sent_for, last_weekly_sent_for, last_monthly_sent_for, updated_at
FROM analytics_email_settings
WHERE enabled = 1 AND email <> '' AND (daily = 1 OR weekly = 1 OR monthly = 1)
ORDER BY user_id`

func (q *Queries) ListEnabledAnalyticsEmailSettings(ctx context.Context) ([]AnalyticsEmailSetting, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAnalyticsEmailSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsEmailSetting{}
	for rows.Next() {
		var i AnalyticsEmailSetting
		if err := rows.Scan(&i.UserID, &i.Enabled, &i.Email, &i.Timezone, &i.Daily, &i.Weekly, &i.Monthly, &i.MetricsJson, &i.LastDailySentFor, &i.LastWeeklySentFor, &i.LastMonthlySentFor, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type UpsertAnalyticsEmailSettingsParams struct {
	UserID      string `json:"user_id"`
	Enabled     int64  `json:"enabled"`
	Email       string `json:"email"`
	Timezone    string `json:"timezone"`
	Daily       int64  `json:"daily"`
	Weekly      int64  `json:"weekly"`
	Monthly     int64  `json:"monthly"`
	MetricsJson string `json:"metrics_json"`
}

const upsertAnalyticsEmailSettings = `INSERT INTO analytics_email_settings (user_id, enabled, email, timezone, daily, weekly, monthly, metrics_json, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
  enabled = excluded.enabled,
  email = excluded.email,
  timezone = excluded.timezone,
  daily = excluded.daily,
  weekly = excluded.weekly,
  monthly = excluded.monthly,
  metrics_json = excluded.metrics_json,
  updated_at = CURRENT_TIMESTAMP
RETURNING user_id, enabled, email, timezone, daily, weekly, monthly, metrics_json, last_daily_sent_for, last_weekly_sent_for, last_monthly_sent_for, updated_at`

func (q *Queries) UpsertAnalyticsEmailSettings(ctx context.Context, arg UpsertAnalyticsEmailSettingsParams) (AnalyticsEmailSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertAnalyticsEmailSettings, arg.UserID, arg.Enabled, arg.Email, arg.Timezone, arg.Daily, arg.Weekly, arg.Monthly, arg.MetricsJson)
	var i AnalyticsEmailSetting
	err := row.Scan(&i.UserID, &i.Enabled, &i.Email, &i.Timezone, &i.Daily, &i.Weekly, &i.Monthly, &i.MetricsJson, &i.LastDailySentFor, &i.LastWeeklySentFor, &i.LastMonthlySentFor, &i.UpdatedAt)
	return i, err
}

type UpdateAnalyticsEmailLastSentParams struct {
	UserID    string `json:"user_id"`
	Frequency string `json:"frequency"`
	PeriodKey string `json:"period_key"`
}

func (q *Queries) UpdateAnalyticsEmailLastSent(ctx context.Context, arg UpdateAnalyticsEmailLastSentParams) error {
	column := "last_daily_sent_for"
	switch arg.Frequency {
	case "weekly":
		column = "last_weekly_sent_for"
	case "monthly":
		column = "last_monthly_sent_for"
	}
	_, err := q.db.ExecContext(ctx, "UPDATE analytics_email_settings SET "+column+" = ?, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?", arg.PeriodKey, arg.UserID)
	return err
}
