// Code generated by sqlc style overlay. DO NOT EDIT BY HAND OUTSIDE THE OVERLAY TASK.
package store

import "context"

const getDailyJournalReminderSettings = `SELECT user_id, enabled, reminder_time, timezone, push_enabled, email_enabled, email, last_sent_for, updated_at
FROM daily_journal_reminders
WHERE user_id = ?`

func (q *Queries) GetDailyJournalReminderSettings(ctx context.Context, userID string) (DailyJournalReminderSetting, error) {
	row := q.db.QueryRowContext(ctx, getDailyJournalReminderSettings, userID)
	var i DailyJournalReminderSetting
	err := row.Scan(&i.UserID, &i.Enabled, &i.ReminderTime, &i.Timezone, &i.PushEnabled, &i.EmailEnabled, &i.Email, &i.LastSentFor, &i.UpdatedAt)
	return i, err
}

const listEnabledDailyJournalReminders = `SELECT user_id, enabled, reminder_time, timezone, push_enabled, email_enabled, email, last_sent_for, updated_at
FROM daily_journal_reminders
WHERE enabled = 1 AND (push_enabled = 1 OR (email_enabled = 1 AND email <> ''))
ORDER BY user_id`

func (q *Queries) ListEnabledDailyJournalReminders(ctx context.Context) ([]DailyJournalReminderSetting, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDailyJournalReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyJournalReminderSetting{}
	for rows.Next() {
		var i DailyJournalReminderSetting
		if err := rows.Scan(&i.UserID, &i.Enabled, &i.ReminderTime, &i.Timezone, &i.PushEnabled, &i.EmailEnabled, &i.Email, &i.LastSentFor, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type UpsertDailyJournalReminderSettingsParams struct {
	UserID       string `json:"user_id"`
	Enabled      int64  `json:"enabled"`
	ReminderTime string `json:"reminder_time"`
	Timezone     string `json:"timezone"`
	PushEnabled  int64  `json:"push_enabled"`
	EmailEnabled int64  `json:"email_enabled"`
	Email        string `json:"email"`
}

const upsertDailyJournalReminderSettings = `INSERT INTO daily_journal_reminders (user_id, enabled, reminder_time, timezone, push_enabled, email_enabled, email, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
  enabled = excluded.enabled,
  reminder_time = excluded.reminder_time,
  timezone = excluded.timezone,
  push_enabled = excluded.push_enabled,
  email_enabled = excluded.email_enabled,
  email = excluded.email,
  updated_at = CURRENT_TIMESTAMP
RETURNING user_id, enabled, reminder_time, timezone, push_enabled, email_enabled, email, last_sent_for, updated_at`

func (q *Queries) UpsertDailyJournalReminderSettings(ctx context.Context, arg UpsertDailyJournalReminderSettingsParams) (DailyJournalReminderSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertDailyJournalReminderSettings, arg.UserID, arg.Enabled, arg.ReminderTime, arg.Timezone, arg.PushEnabled, arg.EmailEnabled, arg.Email)
	var i DailyJournalReminderSetting
	err := row.Scan(&i.UserID, &i.Enabled, &i.ReminderTime, &i.Timezone, &i.PushEnabled, &i.EmailEnabled, &i.Email, &i.LastSentFor, &i.UpdatedAt)
	return i, err
}

type UpdateDailyJournalReminderLastSentParams struct {
	UserID string `json:"user_id"`
	DayKey string `json:"day_key"`
}

func (q *Queries) UpdateDailyJournalReminderLastSent(ctx context.Context, arg UpdateDailyJournalReminderLastSentParams) error {
	_, err := q.db.ExecContext(ctx, `UPDATE daily_journal_reminders SET last_sent_for = ?, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?`, arg.DayKey, arg.UserID)
	return err
}

type JournalDailyLogExistsParams struct {
	UserID string `json:"user_id"`
	DayKey string `json:"day_key"`
}

func (q *Queries) JournalDailyLogExists(ctx context.Context, arg JournalDailyLogExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, `SELECT COUNT(*) FROM journal_notes WHERE user_id = ? AND note_type = 'daily_log' AND substr(occurred_at, 1, 10) = ?`, arg.UserID, arg.DayKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}
