// Code generated by sqlc style overlay. DO NOT EDIT BY HAND OUTSIDE THE OVERLAY TASK.

package store

import (
	"context"
	"database/sql"
	"time"
)

type EconomicCalendarAISetting struct {
	ID           int64     `json:"id"`
	Enabled      int64     `json:"enabled"`
	BaseUrl      string    `json:"base_url"`
	ApiKey       string    `json:"api_key"`
	Model        string    `json:"model"`
	CustomPrompt string    `json:"custom_prompt"`
	UpdatedAt    time.Time `json:"updated_at"`
}

const getEconomicCalendarAISettings = `SELECT id, enabled, base_url, api_key, model, custom_prompt, updated_at
FROM economic_calendar_ai_settings
WHERE id = 1`

func (q *Queries) GetEconomicCalendarAISettings(ctx context.Context) (EconomicCalendarAISetting, error) {
	row := q.db.QueryRowContext(ctx, getEconomicCalendarAISettings)
	var i EconomicCalendarAISetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.CustomPrompt,
		&i.UpdatedAt,
	)
	return i, err
}

type UpsertEconomicCalendarAISettingsParams struct {
	Enabled      int64  `json:"enabled"`
	BaseUrl      string `json:"base_url"`
	ApiKey       string `json:"api_key"`
	Model        string `json:"model"`
	CustomPrompt string `json:"custom_prompt"`
}

const upsertEconomicCalendarAISettings = `INSERT INTO economic_calendar_ai_settings (id, enabled, base_url, api_key, model, custom_prompt, updated_at)
VALUES (1, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    enabled = excluded.enabled,
    base_url = excluded.base_url,
    api_key = excluded.api_key,
    model = excluded.model,
    custom_prompt = excluded.custom_prompt,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, enabled, base_url, api_key, model, custom_prompt, updated_at`

func (q *Queries) UpsertEconomicCalendarAISettings(ctx context.Context, arg UpsertEconomicCalendarAISettingsParams) (EconomicCalendarAISetting, error) {
	row := q.db.QueryRowContext(ctx, upsertEconomicCalendarAISettings,
		arg.Enabled,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Model,
		arg.CustomPrompt,
	)
	var i EconomicCalendarAISetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Model,
		&i.CustomPrompt,
		&i.UpdatedAt,
	)
	if err == sql.ErrNoRows {
		return EconomicCalendarAISetting{}, err
	}
	return i, err
}
