// Code generated by sqlc style overlay. DO NOT EDIT BY HAND OUTSIDE THE OVERLAY TASK.

package store

import (
	"context"
	"time"
)

type SmtpSetting struct {
	ID         int64     `json:"id"`
	Enabled    int64     `json:"enabled"`
	Host       string    `json:"host"`
	Port       int64     `json:"port"`
	Encryption string    `json:"encryption"`
	Username   string    `json:"username"`
	Password   string    `json:"password"`
	FromEmail  string    `json:"from_email"`
	FromName   string    `json:"from_name"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type EmailTemplate struct {
	Key       string    `json:"key"`
	Name      string    `json:"name"`
	Subject   string    `json:"subject"`
	Body      string    `json:"body"`
	UpdatedAt time.Time `json:"updated_at"`
}

const getSmtpSettings = `SELECT id, enabled, host, port, encryption, username, password, from_email, from_name, updated_at
FROM smtp_settings
WHERE id = 1`

func (q *Queries) GetSmtpSettings(ctx context.Context) (SmtpSetting, error) {
	row := q.db.QueryRowContext(ctx, getSmtpSettings)
	var i SmtpSetting
	err := row.Scan(&i.ID, &i.Enabled, &i.Host, &i.Port, &i.Encryption, &i.Username, &i.Password, &i.FromEmail, &i.FromName, &i.UpdatedAt)
	return i, err
}

type UpsertSmtpSettingsParams struct {
	Enabled    int64  `json:"enabled"`
	Host       string `json:"host"`
	Port       int64  `json:"port"`
	Encryption string `json:"encryption"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	FromEmail  string `json:"from_email"`
	FromName   string `json:"from_name"`
}

const upsertSmtpSettings = `INSERT INTO smtp_settings (id, enabled, host, port, encryption, username, password, from_email, from_name, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  enabled = excluded.enabled,
  host = excluded.host,
  port = excluded.port,
  encryption = excluded.encryption,
  username = excluded.username,
  password = excluded.password,
  from_email = excluded.from_email,
  from_name = excluded.from_name,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, enabled, host, port, encryption, username, password, from_email, from_name, updated_at`

func (q *Queries) UpsertSmtpSettings(ctx context.Context, arg UpsertSmtpSettingsParams) (SmtpSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertSmtpSettings, arg.Enabled, arg.Host, arg.Port, arg.Encryption, arg.Username, arg.Password, arg.FromEmail, arg.FromName)
	var i SmtpSetting
	err := row.Scan(&i.ID, &i.Enabled, &i.Host, &i.Port, &i.Encryption, &i.Username, &i.Password, &i.FromEmail, &i.FromName, &i.UpdatedAt)
	return i, err
}

const listEmailTemplates = `SELECT key, name, subject, body, updated_at
FROM email_templates
ORDER BY name ASC`

func (q *Queries) ListEmailTemplates(ctx context.Context) ([]EmailTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listEmailTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailTemplate{}
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(&i.Key, &i.Name, &i.Subject, &i.Body, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type UpsertEmailTemplateParams struct {
	Key     string `json:"key"`
	Name    string `json:"name"`
	Subject string `json:"subject"`
	Body    string `json:"body"`
}

const upsertEmailTemplate = `INSERT INTO email_templates (key, name, subject, body, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET
  name = excluded.name,
  subject = excluded.subject,
  body = excluded.body,
  updated_at = CURRENT_TIMESTAMP
RETURNING key, name, subject, body, updated_at`

func (q *Queries) UpsertEmailTemplate(ctx context.Context, arg UpsertEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRowContext(ctx, upsertEmailTemplate, arg.Key, arg.Name, arg.Subject, arg.Body)
	var i EmailTemplate
	err := row.Scan(&i.Key, &i.Name, &i.Subject, &i.Body, &i.UpdatedAt)
	return i, err
}
