// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_funded_listings.sql

package store

import "context"

const createGetFundedListing = `-- name: CreateGetFundedListing :one
INSERT INTO get_funded_listings (
  id, firm_name, heading, description, content, image_url, affiliate_url, cta_label, promo_code, display_order, published, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, firm_name, heading, description, content, image_url, affiliate_url, cta_label, promo_code, display_order, published, created_at, updated_at
`

type CreateGetFundedListingParams struct {
	ID           string `json:"id"`
	FirmName     string `json:"firm_name"`
	Heading      string `json:"heading"`
	Description  string `json:"description"`
	Content      string `json:"content"`
	ImageUrl     string `json:"image_url"`
	AffiliateUrl string `json:"affiliate_url"`
	CtaLabel     string `json:"cta_label"`
	PromoCode    string `json:"promo_code"`
	DisplayOrder int64  `json:"display_order"`
	Published    int64  `json:"published"`
}

func (q *Queries) CreateGetFundedListing(ctx context.Context, arg CreateGetFundedListingParams) (GetFundedListing, error) {
	row := q.db.QueryRowContext(ctx, createGetFundedListing,
		arg.ID, arg.FirmName, arg.Heading, arg.Description, arg.Content, arg.ImageUrl,
		arg.AffiliateUrl, arg.CtaLabel, arg.PromoCode, arg.DisplayOrder, arg.Published,
	)
	var i GetFundedListing
	err := row.Scan(&i.ID, &i.FirmName, &i.Heading, &i.Description, &i.Content, &i.ImageUrl, &i.AffiliateUrl, &i.CtaLabel, &i.PromoCode, &i.DisplayOrder, &i.Published, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteGetFundedListing = `-- name: DeleteGetFundedListing :execrows
DELETE FROM get_funded_listings
WHERE id = ?
`

func (q *Queries) DeleteGetFundedListing(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGetFundedListing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllGetFundedListings = `-- name: ListAllGetFundedListings :many
SELECT id, firm_name, heading, description, content, image_url, affiliate_url, cta_label, promo_code, display_order, published, created_at, updated_at
FROM get_funded_listings
ORDER BY display_order ASC, created_at DESC
`

func (q *Queries) ListAllGetFundedListings(ctx context.Context) ([]GetFundedListing, error) {
	rows, err := q.db.QueryContext(ctx, listAllGetFundedListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundedListing
	for rows.Next() {
		var i GetFundedListing
		if err := rows.Scan(&i.ID, &i.FirmName, &i.Heading, &i.Description, &i.Content, &i.ImageUrl, &i.AffiliateUrl, &i.CtaLabel, &i.PromoCode, &i.DisplayOrder, &i.Published, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedGetFundedListings = `-- name: ListPublishedGetFundedListings :many
SELECT id, firm_name, heading, description, content, image_url, affiliate_url, cta_label, promo_code, display_order, published, created_at, updated_at
FROM get_funded_listings
WHERE published = 1
ORDER BY display_order ASC, created_at DESC
`

func (q *Queries) ListPublishedGetFundedListings(ctx context.Context) ([]GetFundedListing, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedGetFundedListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFundedListing
	for rows.Next() {
		var i GetFundedListing
		if err := rows.Scan(&i.ID, &i.FirmName, &i.Heading, &i.Description, &i.Content, &i.ImageUrl, &i.AffiliateUrl, &i.CtaLabel, &i.PromoCode, &i.DisplayOrder, &i.Published, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGetFundedListing = `-- name: UpdateGetFundedListing :one
UPDATE get_funded_listings
SET firm_name = ?,
    heading = ?,
    description = ?,
    content = ?,
    image_url = ?,
    affiliate_url = ?,
    cta_label = ?,
    promo_code = ?,
    display_order = ?,
    published = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, firm_name, heading, description, content, image_url, affiliate_url, cta_label, promo_code, display_order, published, created_at, updated_at
`

type UpdateGetFundedListingParams struct {
	FirmName     string `json:"firm_name"`
	Heading      string `json:"heading"`
	Description  string `json:"description"`
	Content      string `json:"content"`
	ImageUrl     string `json:"image_url"`
	AffiliateUrl string `json:"affiliate_url"`
	CtaLabel     string `json:"cta_label"`
	PromoCode    string `json:"promo_code"`
	DisplayOrder int64  `json:"display_order"`
	Published    int64  `json:"published"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateGetFundedListing(ctx context.Context, arg UpdateGetFundedListingParams) (GetFundedListing, error) {
	row := q.db.QueryRowContext(ctx, updateGetFundedListing,
		arg.FirmName, arg.Heading, arg.Description, arg.Content, arg.ImageUrl,
		arg.AffiliateUrl, arg.CtaLabel, arg.PromoCode, arg.DisplayOrder, arg.Published, arg.ID,
	)
	var i GetFundedListing
	err := row.Scan(&i.ID, &i.FirmName, &i.Heading, &i.Description, &i.Content, &i.ImageUrl, &i.AffiliateUrl, &i.CtaLabel, &i.PromoCode, &i.DisplayOrder, &i.Published, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
